providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "openssl", "python3", "redis"]

[phases.install]
cmds = ["npm ci", "python -m venv /opt/venv", ". /opt/venv/bin/activate && pip install --upgrade pip && pip install rembg onnxruntime Pillow"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = ". /opt/venv/bin/activate && redis-server --daemonize yes && npx prisma db push --force-reset && npm run db:seed && npm run start"
